FROM openjdk:17
EXPOSE 8081
ADD target/springboot-aws-deploy-authentication-server.jar springboot-aws-deploy-authentication-server.jar
ENTRYPOINT ["java","-jar","/springboot-aws-deploy-authentication-server.jar"]