#spring:
#  config:
#    import: optional:configserver:http://localhost:9296/

#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: jt-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            value:
#              default:
#                type: 'com.microservices.notificationservice.dtos.MealPlanDTO'
#            type:
#              mapping: 'com.microservices.mealplanservice.dto.mealDto.MealPlanDTO:com.microservices.notificationservice.dtos.MealPlanDTO'
